"""delete personal goal and reason for joining

Revision ID: 3924a098887b
Revises: 0eebc9897e22
Create Date: 2025-07-01 17:48:13.044095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3924a098887b'
down_revision = '0eebc9897e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('reason_for_joining')
        batch_op.drop_column('personal_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_goal', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reason_for_joining', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
