"""delete note, status columns

Revision ID: 5323e9fc7cbc
Revises: 3924a098887b
Create Date: 2025-07-01 21:35:30.662383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5323e9fc7cbc'
down_revision = '3924a098887b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progresslogs', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progresslogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
