"""eliminate nullability habit name

Revision ID: fb466971a48f
Revises: f8c59368bffe
Create Date: 2025-06-28 20:52:09.544348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb466971a48f'
down_revision = 'f8c59368bffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint('habits_name_key', type_='unique')

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_participations_challenge_id_challenges', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_participations_challenge_id_challenges'), 'challenges', ['challenge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_participations_challenge_id_challenges'), type_='foreignkey')
        batch_op.create_foreign_key('fk_participations_challenge_id_challenges', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_unique_constraint('habits_name_key', ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
